name: "Autohand Code CLI"
description: "The world fastest open code cli agent"
url: "https://www.autohand.ai/cli"
docs: "https://autohand.ai/docs/integrations/openrouter" # Link to OpenRouter setup instructions
tags:
  - coding
  - chat
  - research # Choose from: chat, coding, productivity, creative, research, other
open_source: "https://github.com/autohandai/code-cli" # Optional: remove if not open source
date_added: "2026-01-15" # Use today's date in YYYY-MM-DD format
